
name: Deploy Development Environment

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: develop
    steps:
      - name: 🛠️ Checkout code
        uses: actions/checkout@v4
      - name: 🛠️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Write SSH key
        run: | # github actinos의 secrets 사용 시 마지막 개행이 사라짐
          printf "%s\n" "${{ secrets.SSH_KEY }}" > ssh_key
      - name: 🏗️ Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v6
        id: build-push-action
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: SOME_TAG
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secret-files: |
            "ssh_key=ssh_key"
      - name: Clean up
        run: |
          rm -f ssh_key